Review 2023
Logius-standaarden/Digikoppeling-Best-Practices-GB pull request #7
Opened 2023-05-23 16:16 UTC by mrtn78

2023-05-25 13:17 UTC, sanderke requested changes

2023-05-25 13:17 UTC, sanderke commented on ch01_Inleiding.md
> +* interfacedefinitie (voorbeeld)listing van HTTP eb SOAP headers, en
```suggestion
* interfacedefinitie (voorbeeld)listing van HTTP en SOAP headers, en
```

2023-05-25 13:17 UTC, sanderke commented on ch02_Best Practices.md
> +Bij het Melden van grote hoeveelheden informatie kan van ebMS2 gebruik gemaakt te worden. Met ebMS2 kan de ontvangst van de metadata gegarandeerd worden.
```suggestion
Bij het Melden van grote hoeveelheden informatie kan van ebMS2 gebruik gemaakt worden. Met ebMS2 kan de ontvangst van de metadata gegarandeerd worden.
```

2023-05-25 13:17 UTC, sanderke commented on ch02_Best Practices.md
> +Strik genomen moeten zowel de server als de client controleren op correct OIN gebruik. Dit houdt in dat het OIN uit het certificaat dient overeen te komen met de OIN uit het bericht. In praktijk zal
```suggestion
Strikt genomen moeten zowel de server als de client controleren op correct OIN gebruik. Dit houdt in dat het OIN uit het certificaat dient overeen te komen met het OIN uit het bericht. In praktijk zal dit voor de client echter niet altijd noodzakelijk zijn. Ook bij het profiel wordt deze controle niet strikt uitgevoerd en bovendien kun je je afvragen waarom de http-client het OIN van de server moet controleren als net daarvoor metadata met een url is ontvangen van een communicatie-partner waarvan het OIN bij de ontvangst van deze meta-data al gecontroleerd is. Bovendien controleert een TLS-client automatisch of het domein van de server overeenkomt met het certificaat.
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +In deze use case is benodigde gegevens set al beschikbaar in een download-server bij de service provider. De client dient echter nog de beschikking te krijgen over een verwijzing naar de gewenste geg
```suggestion
In deze use case is een benodigde gegevensset al beschikbaar in een download-server bij de service provider. De client dient echter nog de beschikking te krijgen over een verwijzing naar de gewenste gegevensset. Daartoe worden de volgende processtappen doorlopen:
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +1. De service requester / client bevraagt (REST-API, WUS of ebMS2 request) de service provider met kenmerkende criteria voor de gezochte gegevens set. Eventueel kan deze bevraging in enkele tussensta
```suggestion
1. De service requester / client bevraagt (REST-API, WUS of ebMS2 request) de service provider met kenmerkende criteria voor de gezochte gegevensset. Eventueel kan deze bevraging in enkele tussenstappen verlopen als deze initieel te veel mogelijkheden oplevert.
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +3. De service requester haalt de gewenste gegevens set op (Groot Bericht) en krijgt deze op grond van autorisatie (OIN).
```suggestion
3. De service requester haalt de gewenste gegevensset op (Groot Bericht) en krijgt deze op grond van autorisatie (OIN).
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +1. De service requester bevraagt (ebMS2-request of eventueel REST-API of WUS) de service provider met kenmerkende criteria voor de gezochte gegevens set. Eventueel kan deze bevraging in enkele tussen
```suggestion
1. De service requester bevraagt (ebMS2-request of eventueel REST-API of WUS) de service provider met kenmerkende criteria voor de gezochte gegevensset. Eventueel kan deze bevraging in enkele tussenstappen verlopen als deze initieel te veel mogelijkheden oplevert.
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +1. De service requester haalt de gewenste gegevens set op (Groot Bericht) en krijgt deze op grond van autorisatie (OIN).
```suggestion
1. De service requester haalt de gewenste gegevensset op (Groot Bericht) en krijgt deze op grond van autorisatie (OIN).
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +Op enig moment is er een gebeurtenis waardoor de service provider besluit tot verzenden van gegevens. Voorbeelden van triggers zijn: tijd, bericht ontvangst of wijziging van gegevensobjecten.
```suggestion
Op enig moment is er een gebeurtenis waardoor de service provider besluit tot verzenden van gegevens. Voorbeelden van triggers zijn: tijd, berichtontvangst of wijziging van gegevensobjecten.
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +2. De service provider stuurt een 'upload response' met instructies over de upload lokatie (UUID).
```suggestion
2. De service provider stuurt een 'upload response' met instructies over de uploadlocatie (UUID).
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +1. Op enig moment is er een gebeurtenis waardoor de service provider besluit tot distributie van gegevens. Voorbeelden van triggers zijn: tijd, bericht ontvangst of wijziging van gegevensobjecten.
```suggestion
1. Op enig moment is er een gebeurtenis waardoor de service provider besluit tot distributie van gegevens. Voorbeelden van triggers zijn: tijd, berichtontvangst of wijziging van gegevensobjecten.
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +1. Op enig moment is er een gebeurtenis waardoor de service requester besluit tot verzenden van gegevens. Voorbeelden van triggers zijn: tijd, bericht ontvangst of wijziging van gegevensobjecten.
```suggestion
1. Op enig moment is er een gebeurtenis waardoor de service requester besluit tot verzenden van gegevens. Voorbeelden van triggers zijn: tijd, berichtontvangst of wijziging van gegevensobjecten.
```

2023-05-25 13:17 UTC, sanderke commented on ch03_Use cases.md
> +2. Als de gegevens set nog niet beschikbaar is in de vorm van een Groot Bestand zal dit aangemaakt worden (bijvoorbeeld door samenstelling vanuit een database)
```suggestion
2. Als de gegevensset nog niet beschikbaar is in de vorm van een Groot Bestand zal dit aangemaakt worden (bijvoorbeeld door samenstelling vanuit een database)
```

2023-05-25 13:17 UTC, sanderke commented on js/config.js
> +  publishVersion: "3.2",
```suggestion
  publishVersion: "3.2.0",
```
Bij "Documentbeheer" staat `3.2.0`.
https://github.com/Logius-standaarden/Digikoppeling-Best-Practices-GB/blob/90e8e9b99dbe66fd4804e033702dbb1aecb54be2/02_documentbeheer.md?plain=1#L10

2023-05-26 09:48 UTC, mrtn78 reviewed
typo's fixed

2023-05-26 11:11 UTC, sanderke approved these changes

2023-06-08 07:34 UTC, PHaasnoot commented on ch03_Use cases.md
> +1. De service requester haalt de gewenste gegevensset op (Groot Bericht) en krijgt deze op grond van autorisatie (OIN).
opsomming?

2023-06-08 09:38 UTC, PHaasnoot commented on 03_colofon.md
> +| Logius Afdeling Standaarden: | email. digikoppeling@logiuis.nl<br>email. api@logius.nl                                                 |
```suggestion
| Logius Afdeling Standaarden: | email. digikoppeling@logius.nl<br>email. api@logius.nl                                                 |
```

2023-06-08 09:49 UTC, PHaasnoot approved these changes

2023-06-08 09:49 UTC, merged